server:
  port: 80
spring:
  application:
    name: cloud-order-service
  redis:
    password: #没有密码
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100ms
        min-idle: 0
