server:
  port: 80
nacos:
  config:
    server-addr: 127.0.0.1:8848 #配置中心
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #注册中心
  application:
    name: cloud-order-service
  redis:
    password: #没有密码
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100ms
        min-idle: 0
