server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/nicholas-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    password: #没有密码
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100ms
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ning.springcloud.entities.dao